### ISSUE TITLE
ld: file not found : (null): Linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by dante20007** [ParsePlatform/Anypic#33]
Hi,

I'm getting this error when trying to run this iOS project on iOS Simulator.
(null): Linker command failed with exit code 1 (use -v to see invocation)
![capture d ecran 2014-10-22 a 23 44 21](https://cloud.githubusercontent.com/assets/3480728/4744944/e7805b54-5a34-11e4-966e-fdbf15e31b3c.png)

What's wrong ?

**Comment by hramos** [comment]
Try running a clean and build again.
