### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by taylorcam** [ParsePlatform/Anypic#34]
![screen shot 2014-11-02 at 12 53 53](https://cloud.githubusercontent.com/assets/7456457/4875262/1dfbd1c4-628f-11e4-9497-482ac1a7333f.png)
Having a lot of build errors and this is the plane version from Github, can anyone help

**Comment by elieric** [comment]
download the newest Facebook sdk

**Comment by JinOvereasy** [comment]
Hi, i'm also getting an error, but a different one after downloading the newest Facebook sdk. 

"unknown type name 'PFFile'. Anyone also got it?

**Comment by taylorcam** [comment]
@JinOvereasy i'd create a new issue for that :)
