### ISSUE TITLE
Login failure. FB Access Token or user ID does not exist

### ISSUE THREAD

**Issue by FrankCalfran** [ParsePlatform/Anypic#43]
I'm able to run the app on the simulator with no issue (by manually logging in with facebook username and passwords), however, when running the app on a device I get a "Login failure. FB Access Token or user ID does not exist" error (and the app does not progress past the login screen, as the app is trying to login using the facebook app installed on the device. 
Any assistance would be most appreciated.

**Comment by TrentHowser** [comment]
@hramos I'm running into a similar issue. I've worked with previous version of Anypic and am aware of the requirements regarding the App ID steps etc. I've followed all the steps and am able to run the app on a simulator with no errors. In the simulator I log in using the webview popup. But when running it on a device I'm getting the "Login failure. FB Access Token or user ID does not exist" error. 

The app attempts to authorise login via the Facebook app (also installed on the device). It fails and returns to the login screen. The facebook button says "logout" and clicking it i get a "Username logout?" message. So it looks like I'm getting "facebookUserId" but not the "accessToken".

If i remove the facebook app from the device and repeat, login occurs via the webview popup (just like on the simulator) and all is well. I have ensured that the facebook app has authorised anypic to use it (per the facebook app settings). 

The only change I made to the code was removing the "Upload Symbol Files" section per the instructions. Is there a step that i'm missing? I can't imagine so, as I mentioned it works fine if I'm not authorising login via the facebook app.

**Comment by itjunkii** [comment]
Having the same problem.

**Comment by xGoPox** [comment]
Facing the same issue, i am going to investigate, get back to you asap ! :)

**Comment by xGoPox** [comment]
According to the Facebook SDK :

/*!
 @abstract returns the user ID NSString that is associated with the token,if available.
 @discussion This may not be populated for login behaviours such as the iOS system account.
 */
@property (readonly, nonatomic, copy) NSString *userID;

I have changed the method to ( below ) and it is working : 

- (void)loginViewFetchedUserInfo:(FBLoginView *)loginView user:(id<FBGraphUser>)user {

    
    if ([PFUser currentUser]) {
        if (self.delegate && [self.delegate respondsToSelector:@selector(logInViewControllerDidLogUserIn:)]) {
            [self.delegate performSelector:@selector(logInViewControllerDidLogUserIn:) withObject:[PFUser currentUser]];
        }
        return;
    }
        NSString *accessToken = [[[FBSession activeSession] accessTokenData] accessToken];
        NSDate *expirationDate = [[[FBSession activeSession] accessTokenData] expirationDate];
        NSString *facebookUserId = user.objectID;
    
        if (!accessToken || !facebookUserId) {
            NSLog(@"Login failure. FB Access Token or user ID does not exist");
            return;
        }
    
        self.hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
    
        // Unfortunately there are some issues with accessing the session provided from FBLoginView with the Parse SDK's (thread affinity)
        // Just work around this by setting the session to nil, since the relevant values will be discarded anyway when linking with Parse (permissions flag on FBAccessTokenData)
        // that we need to get back again with a refresh of the session
        if ([[FBSession activeSession] respondsToSelector:@selector(clearAffinitizedThread)]) {
            [[FBSession activeSession] performSelector:@selector(clearAffinitizedThread)];
        }
    
        [PFFacebookUtils logInWithFacebookId:facebookUserId
                                 accessToken:accessToken
                              expirationDate:expirationDate
                                       block:^(PFUser *user, NSError *error) {
    
                                           if (!error) {
                                               [self.hud removeFromSuperview];
                                               if (self.delegate) {
                                                   if ([self.delegate respondsToSelector:@selector(logInViewControllerDidLogUserIn:)]) {
                                                       [self.delegate performSelector:@selector(logInViewControllerDidLogUserIn:) withObject:user];
                                                   }
                                               }
                                           } else {
                                               [self cancelLogIn:error];
                                           }
                                       }];



}

**Comment by jeffzira** [comment]
I'm having the same problem. Interestingly enough, it's working fine on an iPhone 5s, but not working on an iPhone 4s. 

I found out that the user ID was null for the 4s. 

xGoPox -- which version of the code are you working on? Also, your post didn't go through super clearly. Are you just changing that one function? 

Thanks

**Comment by ianchakeres** [comment]
I experienced the same issue when a facebook user was logged in via iOS8.1.2 settings on iphone5, and then investigated xGoPox's advice.

I added the method shown below, inside the file PAPLogInViewController.m near where it says " -FBLoginViewDelegate" on top of the latest commit 1892584ea5a63e9a2042298dadaedb4c46d2b7b3.  

I am now able to successfully login.

```
- (void)loginViewFetchedUserInfo:(FBLoginView *)loginView user:(id)user{
  if ([PFUser currentUser]) {
    if (self.delegate && [self.delegate respondsToSelector:@selector(logInViewControllerDidLogUserIn:)]) {
      [self.delegate performSelector:@selector(logInViewControllerDidLogUserIn:) withObject:[PFUser currentUser]];
    }
    return;
  }
  
  NSString *accessToken = [[[FBSession activeSession] accessTokenData] accessToken];
  NSDate *expirationDate = [[[FBSession activeSession] accessTokenData] expirationDate];
  NSString *facebookUserId = [user objectForKey:@"id"];
  
  if (!accessToken || !facebookUserId) {
    NSLog(@"Login failure. FB Access Token or user ID does not exist");
    return;
  }
  
  self.hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
  
  // Unfortunately there are some issues with accessing the session provided from FBLoginView with the Parse SDK's (thread affinity)
  // Just work around this by setting the session to nil, since the relevant values will be discarded anyway when linking with Parse (permissions flag on FBAccessTokenData)
  // that we need to get back again with a refresh of the session
  if ([[FBSession activeSession] respondsToSelector:@selector(clearAffinitizedThread)]) {
    [[FBSession activeSession] performSelector:@selector(clearAffinitizedThread)];
  }
  
  [PFFacebookUtils logInWithFacebookId:facebookUserId
                           accessToken:accessToken
                        expirationDate:expirationDate
                                 block:^(PFUser *user, NSError *error) {
                                   
                                   if (!error) {
                                     [self.hud removeFromSuperview];
                                     if (self.delegate) {
                                       if ([self.delegate respondsToSelector:@selector(logInViewControllerDidLogUserIn:)]) {
                                         [self.delegate performSelector:@selector(logInViewControllerDidLogUserIn:) withObject:user];
                                       }
                                     }
                                   } else {
                                     [self cancelLogIn:error];
                                   }
                                 }];
}

```

**Comment by chamroeunbm** [comment]
Same problem here.

**Comment by andlef** [comment]
have anyone resv the bproblem?

**Comment by stroz** [comment]
Hey, I was having this same issue when running on a device and submitted a support ticket with Facebook. They confirmed that it's an issue when signing in with the Facebook application and recommended using PFFacebookUtils logInWithPermissions as a workaround until they're able to look into it further. I finally was able to login with a device.

```
- (void)handleFacebookSession {
    if ([PFUser currentUser]) {
        if (self.delegate && [self.delegate respondsToSelector:@selector(logInViewControllerDidLogUserIn:)]) {
            [self.delegate performSelector:@selector(logInViewControllerDidLogUserIn:) withObject:[PFUser currentUser]];
        }
        return;
    }

    NSArray *permissionsArray = @[ @"public_profile",
                                   @"user_friends",
                                   @"email"];
    
    self.hud = [MBProgressHUD showHUDAddedTo:self.view animated:YES];
    
    // Login PFUser using Facebook
    [PFFacebookUtils logInWithPermissions:permissionsArray block:^(PFUser *user, NSError *error) {

        if (!user) {
            NSString *errorMessage = nil;
            if (!error) {
                NSLog(@"Uh oh. The user cancelled the Facebook login.");
                errorMessage = @"Uh oh. The user cancelled the Facebook login.";
            } else {
                NSLog(@"Uh oh. An error occurred: %@", error);
                errorMessage = [error localizedDescription];
            }
            UIAlertView *alert = [[UIAlertView alloc] initWithTitle:@"Log In Error"
                                                            message:errorMessage
                                                           delegate:nil
                                                  cancelButtonTitle:nil
                                                  otherButtonTitles:@"Dismiss", nil];
            [alert show];
        } else {
            if (user.isNew) {
                NSLog(@"User with facebook signed up and logged in!");
            } else {
                NSLog(@"User with facebook logged in!");
            }
            
            if (!error) {
                [self.hud removeFromSuperview];
                if (self.delegate) {
                    if ([self.delegate respondsToSelector:@selector(logInViewControllerDidLogUserIn:)]) {
                        [self.delegate performSelector:@selector(logInViewControllerDidLogUserIn:) withObject:user];
                    }
                }
            } else {
                [self cancelLogIn:error];
            }
        }
    }];
}
```

**Comment by jeffreyjackson** [comment]
no need to do all of this.  just switch out the Facebook ID in the info.plist and in the url type.  Be sure to clean your project before you rebuild

**Comment by hramos** [comment]
Hey all, Anypic for iOS is set up to use its own Facebook app. Please make sure to follow the instructions in the README to configure your own Facebook application. Alternatively you may modify the login view controller to use user/password authentication instead.
