### ISSUE TITLE
Push notification on comment activity

### ISSUE THREAD

**Issue by CodeHeroPL** [ParsePlatform/Anypic#47]
I cannot get photo owner to receive comment notification.

I've installed latest version of Anypic from Github and also set up project so that pushes targeted to Everyone work fine. But  `Installation` class in Parse Data lacks `User` reference.

In xcode project in  Application delegate there is `logOut` method that removes user reference like that

`[[PFInstallation currentInstallation] removeObjectForKey:kPAPInstallationUserKey];`

but there is no counterpart setting that `kPAPInstallationUserKey` for `currentInstallation` anywhere in the code. Thus commenting out  ` query.equalTo('user', toUser);` (line 28) in activity.js fixed the pushes for me. However obviously now they are being delivered to all installations...

**Comment by hramos** [comment]
The pointer to user is automatically added by a beforeSave on Parse.Installation in Cloud Code. The instructions to deploy your Cloud Code are covered in the README.
