### ISSUE TITLE
Invalid App ID: FACEBOOK_APP_ID

### ISSUE THREAD

**Issue by gt3240** [ParsePlatform/Anypic#50]
hello, I keep getting this message in iOS safari "Invalid App ID: FACEBOOK_APP_ID".

Please help.

**Comment by Bashta** [comment]
Make sure to enter the right  FACEBOOK_APP_ID.

**Comment by gt3240** [comment]
I'm 110% sure that it's the right ID, I copied and pasted like 10 times.

**Comment by Bashta** [comment]
Its your app on the FB developers page available to the general public?

**Comment by gt3240** [comment]
Yes, it says "This app is public and available to all users" on the FB developers page.

**Comment by Bashta** [comment]
What about the plist? Do the FACEBOOK_APP_ID mathces your FACEBOOK_APP_ID?

**Comment by gt3240** [comment]
Yes, they all match.

**Comment by Bashta** [comment]
Check your app restrictions under settings -> advanced -> app restrictions in your facebook developers page.  The API won't return the app's details unless you make the API call using a user access token for a user who meets whatever restrictions you've applied.

**Comment by gt3240** [comment]
Every thing is off, and the age restriction is anyone.  Thanks for the quick replies.

**Comment by Bashta** [comment]
i'am out of ideas then. Without some more information on the error its difficult to isolate the problem.

**Comment by gt3240** [comment]
does it have to do with the Facebook sdk?  I didn't install the Facebook sdk, I don't think it's needed.

**Comment by Bashta** [comment]
Have you tried to install it?

**Comment by gt3240** [comment]
Yes, but it gave me whole bunch of other errors and the app wouldn't launch, so I removed it.

**Comment by gt3240** [comment]
i'm using the simulator right now

**Comment by gt3240** [comment]
got it working.  =) I had to hard code the Facebook id in [PFFacebookUtils initializeWithApplicationId:@"xxxxxxxxxxxxxxx"];

**Comment by Bashta** [comment]
+1 For the solution!
