### ISSUE TITLE
problems with the iOS version

### ISSUE THREAD

**Issue by outoftrun** [ParsePlatform/Anypic#57]
I pulled the latest version and and attempted to run it under iOS, the code appear to have someone ID and key left in the code and I could not get it to make and run as cleanly as AnyWall. I could not get it change the bundle name it seem to be locked in a release mode with someone else's ID. I have not done as much iOS code as android, so the tools are still a little new to me, but AnyWall came up like a dream and I have made extensive modification to it with no problems.

Nick

**Comment by hramos** [comment]
This is basically the same version of the app that is in the App Store, so it does use the same credentials as that app. The README has some pointers on what needs to be changed if you'd like to run it with your own app keys. We could go back to the same model used for Anywall if that would be prefered by more people.
