### ISSUE TITLE
Podfile missing? 

### ISSUE THREAD

**Issue by johnlabarge** [ParsePlatform/Anypic#65]
Podfile is missing from the Anypic-IOS directory.   Instructions need updating?

**Comment by nlutsenko** [comment]
Hmm. I can see it there in code.
https://github.com/ParsePlatform/Anypic/blob/master/Anypic-iOS/Podfile

Any chance you might have missed it or accidentally removed in your local checkout?

**Comment by johnlabarge** [comment]
My bad.  Some how I pulled down only the 'request' branch.  I have no idea how this happened.
