### ISSUE TITLE
Regarding creating relation 

### ISSUE THREAD

**Issue by ankitguptaiphone** [ParsePlatform/Anypic#67]
HI i am trying to create the class Activity , the parse tutorials show me to create photo----as a Pointer . when i select pointer a option is coming up and ask me to  relate any class with  photo , i have already two custom classes 1) Photo 2 ) User ,  i am trying to attached  both the classed one by one but nothing happen .SImply my question is i don't understand the last option photo----pointer , anyone please explain the last point  . 

Activity

fromUser : User
toUser : User
type : String
content : String
photo : Pointer

**Comment by hramos** [comment]
This will be the pointer to the Photo that the user commented on, or that the user liked. Note that this is only valid when "type" is Comment or Like.

**Comment by facebook-github-bot-4** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
